### ISSUE TITLE
SafeMarket-win32-x64.zip is invalid

### ISSUE THREAD

**Issue by rfikki** [SafeMarket/dapp#2]
Tried downloading the windows zip file but I get an error once it is downloaded.

**Comment by aakilfernandes** [comment]
Are you getting an error trying to unzip the file, or run the .exe?

**Comment by aakilfernandes** [comment]
@rfikki can you try the binary here instead and let me know if it works

https://github.com/SafeMarket/dapp/releases/tag/v0.0.53

**Comment by aakilfernandes** [comment]
This has been fixed with the latest release. Please check it out and let me know if you're still having problems.

https://github.com/SafeMarket/dapp/releases/
