### ISSUE TITLE
Error: KeyStore.generateNewAddress:

### ISSUE THREAD

**Issue by btsfav** [SafeMarket/dapp#4]
TypeError: Cannot read property 'salt' of null(…)
Error: KeyStore.generateNewAddress: No seed set
    at a.2.g.generateNewAddress 

I get this error when I try to set a passphrase to create an account. node seems in sync

**Comment by aakilfernandes** [comment]
Looking into this. Thanks.

Do you remember which version you downloaded?

**Comment by btsfav** [comment]
the most recent 0.4.1

**Comment by aakilfernandes** [comment]
Fixed as of v0.4.5

https://github.com/SafeMarket/dapp/releases/tag/v0.4.5

Thanks for the bug report!
